{{ if and .Values.enabled .Values.ingresses }}
{{ range .Values.ingresses }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .name }}
  annotations:
  {{ if .httpauth }}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: {{ .httpauth.secretName | quote }}
    nginx.ingress.kubernetes.io/auth-realm: {{ .httpauth.message | quote }}
  {{ end }}
  {{ if .permanentRedirect }}
    nginx.ingress.kubernetes.io/permanent-redirect: {{ .permanentRedirect | quote }}
  {{ end }}
spec:
  rules:
  {{ range .rules }}
  - host: {{ .host }}
    http:
      paths:
      - backend:
          serviceName: {{ .serviceName }}
          servicePort: {{ .servicePort }}
  {{ end }}
---
{{ end }}
{{ end }}
