apps:

  - name: anyway-prod
    disableAutoSync: true
    project: anyway
    destinationNamespace: anyway
    source:
      repoURL: 'https://github.com/data-for-change/dfc-k8s.git'
      targetRevision: main
      path: apps/anyway
    sourceVaultPluginHelmValueFiles:
      - values-anyway-prod.yaml
      - values-anyway-auto-updated.yaml

  # temporarily disabled anyway-dev to save resources
#  - name: anyway-dev
#    disableAutoSync: true
#    project: anyway
#    destinationNamespace: anyway-dev
#    source:
#      repoURL: 'https://github.com/data-for-change/dfc-k8s.git'
#      targetRevision: main
#      path: apps/anyway
#    sourceVaultPluginHelmValueFiles:
#      - values-anyway-dev.yaml
#      - values-anyway-auto-updated.yaml
