infra_apps:

  - name: monitoring-kube-prometheus-crds
    disableAutoSync: true
    project: default
    destinationNamespace: monitoring
    source:
      repoURL: https://github.com/prometheus-community/helm-charts.git
      path: charts/kube-prometheus-stack/crds/
      # this version should match version defined in apps/monitoring/Chart.yaml
      targetRevision: kube-prometheus-stack-39.11.0
      directory:
        recurse: true

  - name: monitoring
    disableAutoSync: true
    project: default
    destinationNamespace: monitoring
    source:
      repoURL: 'https://github.com/data-for-change/dfc-k8s.git'
      targetRevision: main
      path: apps/monitoring
    sourceVaultPluginHelmValueFiles:
      - values-main.yaml

  - name: logging
    disableAutoSync: true
    project: default
    destinationNamespace: logging
    source:
      repoURL: 'https://github.com/data-for-change/dfc-k8s.git'
      targetRevision: main
      path: apps/logging
    sourceVaultPluginHelmValueFiles:
      - values-main.yaml

  - name: velero-backups
    project: default
    destinationNamespace: velero
    source:
      repoURL: 'https://github.com/data-for-change/dfc-k8s.git'
      targetRevision: main
      path: apps/velero-backups

  - name: vault
    project: default
    destinationNamespace: vault
    source:
      repoURL: 'https://github.com/data-for-change/dfc-k8s.git'
      targetRevision: main
      path: apps/vault

  - name: ingress-nginx
    project: default
    destinationNamespace: ingress-nginx
    source:
      repoURL: 'https://github.com/data-for-change/dfc-k8s.git'
      targetRevision: main
      path: apps/ingress-nginx
