apps:

  - name: anyway-prod
    disableAutoSync: false
    project: anyway
    destinationNamespace: anyway
    source:
      repoURL: 'https://github.com/data-for-change/dfc-k8s.git'
      targetRevision: main
      path: apps/anyway
    sourceVaultPluginHelmValueFiles:
      - values-anyway-prod.yaml
      - values-anyway-auto-updated.yaml

  - name: anyway-dev
    disableAutoSync: false
    project: anyway
    destinationNamespace: anyway-dev
    source:
      repoURL: 'https://github.com/data-for-change/dfc-k8s.git'
      targetRevision: main
      path: apps/anyway
    sourceVaultPluginHelmValueFiles:
      - values-anyway-dev.yaml
      - values-anyway-auto-updated.yaml
