apps:

  - name: monitoring
    disableAutoSync: true
    project: default
    destinationNamespace: monitoring
    source:
      repoURL: 'https://github.com/data-for-change/dfc-k8s.git'
      targetRevision: main
      path: apps/monitoring
    sourceVaultPluginHelmValueFiles:
      - values-main.yaml
