apps:

  - name: argocd-install
    destinationNamespace: argocd
    # best not to autosync core infra components like this to prevent accidental problems
    enableAutoSync: false
    source:
      repoURL: 'git@github.com:data-for-change/data-for-change-k8s.git'
      targetRevision: master
      path: apps/argocd-install

  - name: vault
    destinationNamespace: vault
    # best not to autosync core infra components like this to prevent accidental problems
    enableAutoSync: false
    source:
      repoURL: 'git@github.com:data-for-change/data-for-change-k8s.git'
      targetRevision: master
      path: apps/vault
      helm:
        valueFiles:
          - values-prod.yaml

  - name: velero-backups
    destinationNamespace: velero
    # best not to autosync core infra components like this to prevent accidental problems
    enableAutoSync: false
    source:
      repoURL: 'git@github.com:data-for-change/data-for-change-k8s.git'
      targetRevision: master
      path: apps/velero-backups
