projects:

  - name: anyway
    spec:
      destinations:
        - name: '*'
          namespace: anyway
          server: 'https://kubernetes.default.svc'
        - name: '*'
          namespace: anyway-dev
          server: 'https://kubernetes.default.svc'
      sourceRepos:
        - 'https://github.com/data-for-change/dfc-k8s.git'
