apiVersion: v1
kind: ConfigMap
metadata:
  name: chrome-node-nginx-config
data:
    default.conf: |
      server {
        listen       80;
        server_name  localhost;
        location /tempdata {
          root /var/selenium/tempdata;
          index index.html index.htm;
          autoindex on;
          autoindex_format json;
        }
      }
