apiVersion: batch/v1
kind: CronJob
metadata:
  name: chrome-node-restart
spec:
  schedule: "3 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: chrome-node-restart
          containers:
          - name: kubectl
            # Pulled April 17, 2023
            image: bitnami/kubectl@sha256:670fe3f50d45c0511bb0f2af018e2fc082ac8cdfaea02dba4e32866296036926
            command:
            - /bin/sh
            - -c
            - kubectl rollout restart deployment selenium-chrome-node -n selenium
          restartPolicy: OnFailure
