apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-chrome-node
  labels:
    app: selenium-chrome-node
    app.kubernetes.io/instance: selenium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-chrome-node
      app.kubernetes.io/instance: selenium
  template:
    metadata:
      labels:
        app: selenium-chrome-node
        app.kubernetes.io/instance: selenium
    spec:
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
        - name: tempdata
          emptyDir: {}
        - name: nginxconf
          configMap:
            name: chrome-node-nginx-config
      containers:
        - name: selenium-chrome-node
          image: selenium/node-chrome:4.8.3-20230403
          ports:
            - containerPort: 5555
              protocol: TCP
          envFrom:
            - configMapRef:
                name: selenium-event-bus-config
          resources:
            requests:
              cpu: 300m
              memory: 1500Mi
            limits:
              memory: 2000Mi
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - name: tempdata
              mountPath: /var/selenium/tempdata
        - name: nginx
          image: nginx
          volumeMounts:
            - name: tempdata
              mountPath: /var/selenium/tempdata
            - name: nginxconf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      terminationGracePeriodSeconds: 30
