apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  ports:
  - name: "terraform-state-db"
    port: 9001
    targetPort: 9001
  - name: "anyway-prod-db"
    port: 9002
    targetPort: 9002
  - name: "anyway-dev-db"
    port: 9003
    targetPort: 9003
