apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      containers:
      - name: argocd-repo-server
        # Built from apps/argocd-install/plugin Sep 7, 2022
        image: ghcr.io/data-for-change/dfc-k8s-argocd:5bdac3baf0cf39cf794bbb439875814d27405087@sha256:18ca005ee504ea666fa1667f87488ad1f9513ebffa18b833b6c632f32e4a35d1
        volumeMounts:
        - name: custom-tools
          mountPath: /usr/local/bin/argocd-dfc-plugin
          subPath: argocd-dfc-plugin
      volumes:
      - name: custom-tools
        emptyDir: {}
      initContainers:
      - name: download-tools
        image: alpine:3.8
        command: [sh, -c]

        # Don't forget to update this to whatever the stable release version is
        # Note the lack of the `v` prefix unlike the git tag
        env:
          - name: AVP_VERSION
            value: "1.10.1"
        args:
          - >-
            wget -O argocd-dfc-plugin
            https://raw.githubusercontent.com/data-for-change/dfc-k8s/main/apps/argocd-install/argocd-dfc-plugin.py &&
            chmod +x argocd-dfc-plugin &&
            mv argocd-dfc-plugin /custom-tools/
        volumeMounts:
          - mountPath: /custom-tools
            name: custom-tools

      automountServiceAccountToken: true
      serviceAccountName: argocd-server
