apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dfc-k8s-argocd-apps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: 'https://github.com/data-for-change/dfc-k8s.git'
    targetRevision: main
    path: apps/argocd-apps
    helm:
      valueFiles:
        - values-prod-infra-apps.yaml
        - values-prod-projects.yaml
        - values-prod-apps.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
