apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- install.yaml

patchesStrategicMerge:
- argocd-server-deployment.yaml
- argocd-repo-server-deploy.yaml
- argocd-cm.yaml
- argocd-rbac-cm.yaml
