apiVersion: v1
kind: ConfigMap
metadata:
  name: redash
data:
  PYTHONUNBUFFERED: "0"
  REDASH_LOG_LEVEL: "INFO"
  REDASH_REDIS_URL: "redis://redis:6379/0"
  nginx-default.conf: |
    upstream redash {
      server redash:5000;
    }

    server {
      listen   80 default;

      gzip on;
      gzip_types *;
      gzip_proxied any;
      proxy_buffer_size 8k;

      location / {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;

        proxy_pass       http://redash;
      }
    }
