{{ if and .Values.enabled .Values.ingresses }}
{{ range .Values.ingresses }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}
  annotations:
  {{ if .httpauth }}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: {{ .httpauth.secretName | quote }}
    nginx.ingress.kubernetes.io/auth-realm: {{ .httpauth.message | quote }}
  {{ end }}
  {{ if .permanentRedirect }}
    nginx.ingress.kubernetes.io/permanent-redirect: {{ .permanentRedirect | quote }}
  {{ end }}
spec:
  ingressClassName: nginx
  rules:
  {{ range .rules }}
  - host: {{ .host }}
    http:
      paths:
      - backend:
          service:
            name: {{ .serviceName }}
            port:
              number: {{ .servicePort }}
        pathType: Prefix
        path: /
  {{ end }}
---
{{ end }}
{{ end }}
