kind: ClusterConfig
apiVersion: eksctl.io/v1alpha5

metadata:
  name: main
  region: eu-central-1
  version: "1.22"
  tags:
    dfc-k8s: main

managedNodeGroups:
  - name: ng-2
    # 2 cpu, 16gb ram
    instanceType: r5.large
    minSize: 3
    desiredCapacity: 3
    maxSize: 3
    availabilityZones: ["eu-central-1b"]
    volumeSize: 200
    iam:
      withAddonPolicies:
        autoScaler: true
