apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: monthly
  namespace: velero
spec:
  schedule: '31 1 1 * *'  # 1:31 AM on the first of the month
  template:
    includedNamespaces: ['*']
    ttl: '800h0m0s'
