{{ range (concat .Values.apps .Values.infra_apps) }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name | quote }}
  namespace: argocd
spec:
  destination:
    namespace: {{ if .destinationNamespace }}{{ .destinationNamespace | quote }}{{ else }}{{ .name | quote }}{{ end }}
    {{ if .destinationClusterName }}
    name: {{ .destinationClusterName | quote }}
    {{ else }}
    server: 'https://kubernetes.default.svc'
    {{ end }}
  project: {{ if .project }}{{ .project | quote }}{{ else }}{{ .name | quote }}{{ end }}
  source: {{ toYaml .source | nindent 4 }}
  {{ if or .sourceVaultPluginHelmValueFiles .sourceVaultPluginExtraHelmArgs }}
    plugin:
      name: argocd-vault-plugin-helm-with-args
      env:
        - name: helm_args
          value: {{ range .sourceVaultPluginHelmValueFiles }} -f {{ . }} {{ end }}{{ .sourceVaultPluginExtraHelmArgs | join " " }}
  {{ end }}
  syncPolicy:
    {{ if not $.Values.globalDisableAutoSync }}
    {{ if not .disableAutoSync }}
    automated:
      prune: true
      selfHeal: true
    {{ end }}
    {{ end }}
    syncOptions:
      - CreateNamespace=true
---
{{ end }}