{{ if .Values.enableAirflow }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-home-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
{{ end }}
