{{ if .Values.enableAirflow }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-etl-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
{{ end }}
