{{ if .Values.enableAirflow }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
{{ end }}
