{{ if and .Values.enabled .Values.dbBackupEnabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup
spec:
  schedule: {{ .Values.dbBackupSchedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: db-backup
            image: {{ .Values.pinDbBackupImage | quote }}
            resources: {{ .Values.dbBackupResources }}
            envFrom:
              - secretRef: {"name": "db-backup"}
            env:
              - name: DBDUMP_S3_FILE_PREFIX
                value: {{ .Values.DBDUMP_S3_FILE_PREFIX | quote }}
              - name: DBDUMP_HOST
                value: "db"
              - name: DBDUMP_USER
                value: "postgres"
              - name: DBDUMP_FULL_BUCKET
                value: {{ .Values.DBDUMP_FULL_BUCKET | quote }}
              - name: DBDUMP_PARTIAL_BUCKET
                value: {{ .Values.DBDUMP_PARTIAL_BUCKET | quote }}
{{ end }}
