{{ if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: db
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db
    spec:
      terminationGracePeriodSeconds: 10
      {{ if .Values.dbNodeSelector }}
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.dbNodeSelector }}
      {{ end }}
      containers:
      - name: db
        # we don't want to auto-update the DB!
        image: docker.pkg.github.com/hasadna/anyway/db:sha-168b027
        resources: {{ .Values.dbResources }}
        ports:
          - containerPort: 5432
        envFrom:
          - secretRef: {"name": "db"}
        env:
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_DB
            value: "postgres"
          - name: DBRESTORE_AWS_BUCKET
            value: {{ .Values.dbRestoreBucket | quote }}
          - name: DBRESTORE_FILE_NAME
            value: {{ .Values.dbRestoreFileName | quote }}
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
          # postgres doesn't let you use the root of a disk (it complaints about having lost+found directory)
          subPath: dbdata
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: db
{{ end }}
