{{ if .Values.dbNodePort }}
apiVersion: v1
kind: Service
metadata:
  name: db-nodeport
spec:
  type: NodePort
  selector:
    app: db
  ports:
  - name: "5432"
    port: 5432
    nodePort: {{  .Values.dbNodePort }}
{{ end }}
