{{ if .Values.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.dbPvcName | quote }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
{{ end }}
