apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
data:
  anyway_proxy.conf: |
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto {{ .Values.nginxForwardedScheme }};
    proxy_set_header X-Forwarded-Host {{ .Values.nginxForwardedHost }};
    proxy_pass http://anyway;
    proxy_redirect default;
