{{ if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/nginx-configmap.yaml") . | sha256sum }}
    spec:
      terminationGracePeriodSeconds: 2
      imagePullSecrets: [{"name":"github"}]
      containers:
      - name: nginx
        image: {{ if .Values.useDevImages }}{{ .Values.nginxImageDev }}{{ else }}{{ .Values.nginxImage }}{{ end }}
        resources: {{ .Values.nginxResources }}
        volumeMounts:
        - name: conf
          mountPath: /etc/nginx/anyway_proxy.conf
          subPath: anyway_proxy.conf
      volumes:
      - name: conf
        configMap:
          name: nginx
{{ end }}
