enabled: true
redashImage: redash/redash:8.0.0.b32245
redashInitialize: ""

server:
  resources: {"requests": {"memory": "200Mi"}, "limits": {"memory": "400Mi"}}
  REDASH_WEB_WORKERS: "1"

scheduler:
  resources: {}

scheduledWorker:
  resources: {"requests": {"memory": "100Mi"}, "limits": {"memory": "200Mi"}}

adhocWorker:
  resources: {"requests": {"memory": "700Mi"}, "limits": {"memory": "1000Mi"}}
  WORKERS_COUNT: 2

redis:
  resources: {}

postgres:
  resources: {"requests": {"memory": "200Mi"}, "limits": {"memory": "500Mi"}}

nginx:
  resources: {}

ingresses:
  - name: nginx
    ssl: true
    rules:
      - host: redash.dataforchange.org.il
        serviceName: nginx
        servicePort: 80

secrets:
  - name: redash
    data:
      POSTGRES_PASSWORD: "~vault:projects/k8s/redash/secret:postgres_password~"
      REDASH_COOKIE_SECRET: "~vault:projects/k8s/redash/secret:cookie_secret~"
      REDASH_SECRET_KEY: "~vault:projects/k8s/redash/secret:secret_key~"
      REDASH_DATABASE_URL: "~vault:projects/k8s/redash/secret:redash_database_url~"
      REDASH_GOOGLE_CLIENT_ID: "~vault:projects/k8s/redash/secret:google_auth_client_id~"
      REDASH_GOOGLE_CLIENT_SECRET: "~vault:projects/k8s/redash/secret:google_auth_client_secret~"
