enabled: true
enableSecondaries: false
secondaryReplicas: 0
nginxForwardedHost: "dev.anyway.co.il"
nginxForwardedScheme: "https"
mountGoogleApplicationCredentialsSecret: true
mainResources: '{"requests": {"cpu": "25m", "memory": "684Mi"}, "limits": {"cpu": "78m", "memory": "1500Mi"}}'
secondariesResources: '{"requests": {"cpu": "25m", "memory": "933Mi"}, "limits": {"cpu": "78m", "memory": "1500Mi"}}'
dbResources: '{"requests": {"cpu": "25m", "memory": "2062Mi"}, "limits": {"cpu": "165m", "memory": "3500Mi"}}'
nginxResources: '{"requests": {"cpu": "25m", "memory": "256Mi"}, "limits": {"cpu": "78m", "memory": "500Mi"}}'
DBDUMP_S3_FILE_PREFIX: ""
dbBackupEnabled: false
dbBackupResources: '{"requests": {"cpu": "25m", "memory": "700Mi"}, "limits": {"cpu": "165m", "memory": "1000Mi"}}'
dbBackupSchedule: "10 0 * * *"
dbNodePort: 30735
dbRestoreBucket: "anyway-full-db-dumps"
dbRestoreFileName: "2021-10-10_anyway.pgdump"
useDevImages: true

reports:
  enabled: false
  replicas: 1
  resources: '{"requests": {"cpu": "25m", "memory": "256Mi"}, "limits": {"cpu": "78m", "memory": "500Mi"}}'

enableAirflow: true
airflowDb:
  # pulled August 8, 2021
  image: "postgres:13@sha256:6647385dd9ae11aa2216bf55c54d126b0a85637b3cf4039ef24e3234113588e3"
  resources: {"requests": {"cpu": "50m", "memory": "300Mi"}, "limits": {"memory": "700Mi"}}
airflowImageDev: "docker.pkg.github.com/hasadna/anyway-etl/anyway-etl-airflow:latest"
airflowScheduler:
  resources: {"requests": {"cpu": "300m", "memory": "500Mi"}, "limits": {"memory": "1000Mi"}}
airflowWebserver:
  resources: {"requests": {"cpu": "50m", "memory": "300Mi"}, "limits": {"memory": "700Mi"}}
etlNginxImageDev: "docker.pkg.github.com/hasadna/anyway-etl/anyway-etl-nginx:latest"
etlNginxResources: {"requests": {"cpu": "50m", "memory": "100Mi"}, "limits": {"memory": "200Mi"}}
ANYWAY_ETL_BRANCH: "main"
ANYWAY_ETL_USE_LATEST_TAG: "no"
ANYWAY_KUBECTL_NAMESPACE: "anyway-dev"
AIRFLOW__SMTP__SMTP_MAIL_FROM: "Dev Airflow <dev-airflow@anyway.co.il>"
AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "True"
AIRFLOW__WEBSERVER__BASE_URL: https://dev-airflow.anyway.co.il

ingresses:
  - name: nginx
    rules:
      - host: dev.anyway.co.il
        serviceName: nginx
        servicePort: 80
      # - host: reports.anyway.co.il
      #   serviceName: reports
      #   servicePort: 80
  # - name: redirect
  #   ssl: true
  #   permanentRedirect: https://www.anyway.co.il
  #   rules:
  #     - host: anyway.co.il
  #       serviceName: nginx
  #       servicePort: 80
  #     - host: www.oway.org.il
  #       serviceName: nginx
  #       servicePort: 80
  #     - host: oway.org.il
  #       serviceName: nginx
  #       servicePort: 80
  - name: airflow
    ssl: true
    rules:
      - host: dev-airflow.anyway.co.il
        serviceName: airflow-scheduler
        servicePort: 8080
  - name: airflow-data
    ssl: true
    rules:
      - host: dev-airflow-data.anyway.co.il
        serviceName: airflow-scheduler
        servicePort: 80

secrets:
  - name: anyway
    data:
      AIRFLOW_ADMIN_PASSWORD: "~vault:projects/anyway/dev/k8s-secret-anyway:AIRFLOW_ADMIN_PASSWORD~"
      AIRFLOW_DB_POSTGRES_PASSWORD: "~vault:projects/anyway/dev/k8s-secret-anyway:AIRFLOW_DB_POSTGRES_PASSWORD~"
      AIRFLOW_SQLALCHEMY_URL: "~vault:projects/anyway/dev/k8s-secret-anyway:AIRFLOW_SQLALCHEMY_URL~"
      AIRFLOW__SMTP__SMTP_HOST: "~vault:projects/anyway/dev/k8s-secret-anyway:AIRFLOW__SMTP__SMTP_HOST~"
      AIRFLOW__SMTP__SMTP_PASSWORD: "~vault:projects/anyway/dev/k8s-secret-anyway:AIRFLOW__SMTP__SMTP_PASSWORD~"
      AIRFLOW__SMTP__SMTP_USER: "~vault:projects/anyway/dev/k8s-secret-anyway:AIRFLOW__SMTP__SMTP_USER~"
      ANYWAY_ETL_ALERT_EMAILS: "~vault:projects/anyway/dev/k8s-secret-anyway:ANYWAY_ETL_ALERT_EMAILS~"
      APP_SECRET_KEY: "~vault:projects/anyway/dev/k8s-secret-anyway:APP_SECRET_KEY~"
      AWS_ACCESS_KEY: "~vault:projects/anyway/dev/k8s-secret-anyway:AWS_ACCESS_KEY~"
      AWS_SECRET_KEY: "~vault:projects/anyway/dev/k8s-secret-anyway:AWS_SECRET_KEY~"
      FACEBOOK_KEY: "~vault:projects/anyway/dev/k8s-secret-anyway:FACEBOOK_KEY~"
      FACEBOOK_SECRET: "~vault:projects/anyway/dev/k8s-secret-anyway:FACEBOOK_SECRET~"
      FLASK_ENV: "~vault:projects/anyway/dev/k8s-secret-anyway:FLASK_ENV~"
      GOOGLE_APPLICATION_CREDENTIALS_KEY.json: "~vault:projects/anyway/dev/k8s-secret-anyway:GOOGLE_APPLICATION_CREDENTIALS_KEY~"
      GOOGLE_LOGIN_CLIENT_ID: "~vault:projects/anyway/dev/k8s-secret-anyway:GOOGLE_LOGIN_CLIENT_ID~"
      GOOGLE_LOGIN_CLIENT_SECRET: "~vault:projects/anyway/dev/k8s-secret-anyway:GOOGLE_LOGIN_CLIENT_SECRET~"
      GOOGLE_MAPS_KEY: "~vault:projects/anyway/dev/k8s-secret-anyway:GOOGLE_MAPS_KEY~"
      MAILPASS: "~vault:projects/anyway/dev/k8s-secret-anyway:MAILPASS~"
      MAILUSER: "~vault:projects/anyway/dev/k8s-secret-anyway:MAILUSER~"
      SERVER_ENV: "~vault:projects/anyway/dev/k8s-secret-anyway:SERVER_ENV~"
      TWITTER_ACCESS_KEY: "~vault:projects/anyway/dev/k8s-secret-anyway:TWITTER_ACCESS_KEY~"
      TWITTER_ACCESS_SECRET: "~vault:projects/anyway/dev/k8s-secret-anyway:TWITTER_ACCESS_SECRET~"
      TWITTER_CONSUMER_KEY: "~vault:projects/anyway/dev/k8s-secret-anyway:TWITTER_CONSUMER_KEY~"
      TWITTER_CONSUMER_SECRET: "~vault:projects/anyway/dev/k8s-secret-anyway:TWITTER_CONSUMER_SECRET~"
  - name: anyway-db
    data:
      DATABASE_URL: "~vault:projects/anyway/dev/k8s-secret-anyway-db:DATABASE_URL~"
  - name: db
    data:
      DBRESTORE_AWS_ACCESS_KEY_ID: "~vault:projects/anyway/dev/k8s-secret-db:DBRESTORE_AWS_ACCESS_KEY_ID~"
      DBRESTORE_AWS_SECRET_ACCESS_KEY: "~vault:projects/anyway/dev/k8s-secret-db:DBRESTORE_AWS_SECRET_ACCESS_KEY~"
      DBRESTORE_SET_ANYWAY_PASSWORD: "~vault:projects/anyway/dev/k8s-secret-db:DBRESTORE_SET_ANYWAY_PASSWORD~"
      POSTGRES_PASSWORD: "~vault:projects/anyway/dev/k8s-secret-db:POSTGRES_PASSWORD~"
