enabled: true
enableSecondaries: true
secondaryReplicas: 2
nginxForwardedHost: "www.anyway.co.il"
nginxForwardedScheme: "https"
mountGoogleApplicationCredentialsSecret: true
mainResources: '{"requests": {"cpu": "100m", "memory": "1000Mi"}, "limits": {"cpu": "150m", "memory": "1500Mi"}}'
secondariesResources: '{"requests": {"cpu": "100m", "memory": "1000Mi"}, "limits": {"cpu": "150m", "memory": "1500Mi"}}'
dbResources: '{"requests": {"cpu": "500m", "memory": "3000Mi"}, "limits": {"cpu": "1000m", "memory": "4000Mi"}}'
dbShmSize: "1024Mi"
nginxResources: '{"requests": {"cpu": "25m", "memory": "256Mi"}, "limits": {"cpu": "78m", "memory": "500Mi"}}'
DBDUMP_S3_FILE_PREFIX: ""
dbBackupEnabled: true
dbBackupResources: '{"requests": {"cpu": "25m", "memory": "700Mi"}, "limits": {"cpu": "165m", "memory": "1000Mi"}}'
dbBackupSchedule: "10 0 * * *"
enableLogs: true
dbRestoreBucket: "dfc-anyway-full-db-dumps"
dbRestoreFileName: "2022-12-11_anyway.pgdump"
DBDUMP_FULL_BUCKET: "~iac:anyway_full_db_dumps_bucket~"
DBDUMP_PARTIAL_BUCKET: "~iac:anyway_partial_db_dumps_bucket~"
dbPvcName: "db2"

# we are pinning the DB versions so they won't be upgraded automatically
# these builds are from this commit - https://github.com/hasadna/anyway/commit/6dfd43b
pinDbImage: docker.pkg.github.com/hasadna/anyway/db:sha-6dfd43b
pinDbBackupImage: docker.pkg.github.com/hasadna/anyway/db_backup:sha-6dfd43b

reports:
  enabled: true
  replicas: 1
  resources: '{"requests": {"cpu": "25m", "memory": "256Mi"}, "limits": {"cpu": "78m", "memory": "500Mi"}}'

enableAirflow: true
airflowDb:
  # pulled August 8, 2021
  image: "postgres:13@sha256:6647385dd9ae11aa2216bf55c54d126b0a85637b3cf4039ef24e3234113588e3"
  resources: {"requests": {"cpu": "50m", "memory": "300Mi"}, "limits": {"memory": "700Mi"}}
airflowImage: "docker.pkg.github.com/hasadna/anyway-etl/anyway-etl-airflow:latest"
airflowScheduler:
  resources: {"requests": {"cpu": "300m", "memory": "500Mi"}, "limits": {"memory": "1000Mi"}}
airflowWebserver:
  resources: {"requests": {"cpu": "300m", "memory": "1000Mi"}, "limits": {"memory": "1500Mi"}}
etlNginxImage: "docker.pkg.github.com/hasadna/anyway-etl/anyway-etl-nginx:latest"
etlNginxResources: {"requests": {"cpu": "50m", "memory": "100Mi"}, "limits": {"memory": "200Mi"}}
ANYWAY_ETL_BRANCH: ""
ANYWAY_ETL_USE_LATEST_TAG: "yes"
ANYWAY_KUBECTL_NAMESPACE: "anyway"
AIRFLOW__SMTP__SMTP_MAIL_FROM: "Airflow <airflow@anyway.co.il>"
AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "False"
AIRFLOW__WEBSERVER__BASE_URL: https://airflow.anyway.co.il

ingresses:
  - name: nginx
    ssl: true
    rules:
      - host: www.anyway.co.il
        serviceName: nginx
        servicePort: 80
      - host: reports.anyway.co.il
        serviceName: reports
        servicePort: 80
  - name: redirect
    permanentRedirect: https://www.anyway.co.il
    rules:
      - host: anyway.co.il
        serviceName: nginx
        servicePort: 80
      - host: www.oway.org.il
        serviceName: nginx
        servicePort: 80
      - host: oway.org.il
        serviceName: nginx
        servicePort: 80
  - name: airflow
    ssl: true
    rules:
      - host: airflow.anyway.co.il
        serviceName: airflow-scheduler
        servicePort: 8080
  - name: airflow-data
    ssl: true
    rules:
      - host: airflow-data.anyway.co.il
        serviceName: airflow-scheduler
        servicePort: 80

secrets:
  - name: anyway
    data:
      AIRFLOW_ADMIN_PASSWORD: "~vault:projects/anyway/prod/k8s-secret-anyway:AIRFLOW_ADMIN_PASSWORD~"
      AIRFLOW_DB_POSTGRES_PASSWORD: "~vault:projects/anyway/prod/k8s-secret-anyway:AIRFLOW_DB_POSTGRES_PASSWORD~"
      AIRFLOW_SQLALCHEMY_URL: "~vault:projects/anyway/prod/k8s-secret-anyway:AIRFLOW_SQLALCHEMY_URL~"
      AIRFLOW__SMTP__SMTP_HOST: "~vault:projects/anyway/prod/k8s-secret-anyway:AIRFLOW__SMTP__SMTP_HOST~"
      AIRFLOW__SMTP__SMTP_PASSWORD: "~vault:projects/anyway/prod/k8s-secret-anyway:AIRFLOW__SMTP__SMTP_PASSWORD~"
      AIRFLOW__SMTP__SMTP_USER: "~vault:projects/anyway/prod/k8s-secret-anyway:AIRFLOW__SMTP__SMTP_USER~"
      ANYWAY_ETL_ALERT_EMAILS: "~vault:projects/anyway/prod/k8s-secret-anyway:ANYWAY_ETL_ALERT_EMAILS~"
      APP_SECRET_KEY: "~vault:projects/anyway/prod/k8s-secret-anyway:APP_SECRET_KEY~"
      AWS_ACCESS_KEY: "~vault:projects/anyway/prod/aws_prod_app_user:access_key_id~"
      AWS_SECRET_KEY: "~vault:projects/anyway/prod/aws_prod_app_user:secret_access_key~"
      FACEBOOK_KEY: "~vault:projects/anyway/prod/k8s-secret-anyway:FACEBOOK_KEY~"
      FACEBOOK_SECRET: "~vault:projects/anyway/prod/k8s-secret-anyway:FACEBOOK_SECRET~"
      FLASK_ENV: "~vault:projects/anyway/prod/k8s-secret-anyway:FLASK_ENV~"
      "GOOGLE_APPLICATION_CREDENTIALS_KEY.json": "~vault:projects/anyway/prod/k8s-secret-anyway:GOOGLE_APPLICATION_CREDENTIALS_KEY.json~"
      GOOGLE_LOGIN_CLIENT_ID: "~vault:projects/anyway/prod/k8s-secret-anyway:GOOGLE_LOGIN_CLIENT_ID~"
      GOOGLE_LOGIN_CLIENT_SECRET: "~vault:projects/anyway/prod/k8s-secret-anyway:GOOGLE_LOGIN_CLIENT_SECRET~"
      GOOGLE_MAPS_KEY: "~vault:projects/anyway/prod/k8s-secret-anyway:GOOGLE_MAPS_KEY~"
      MAILPASS: "~vault:projects/anyway/prod/k8s-secret-anyway:MAILPASS~"
      MAILUSER: "~vault:projects/anyway/prod/k8s-secret-anyway:MAILUSER~"
      SERVER_ENV: "~vault:projects/anyway/prod/k8s-secret-anyway:SERVER_ENV~"
      SLACK_WEBHOOK_URL: "~vault:projects/anyway/prod/k8s-secret-anyway:SLACK_WEBHOOK_URL~"
      TWITTER_ACCESS_KEY: "~vault:projects/anyway/prod/k8s-secret-anyway:TWITTER_ACCESS_KEY~"
      TWITTER_ACCESS_SECRET: "~vault:projects/anyway/prod/k8s-secret-anyway:TWITTER_ACCESS_SECRET~"
      TWITTER_CONSUMER_KEY: "~vault:projects/anyway/prod/k8s-secret-anyway:TWITTER_CONSUMER_KEY~"
      TWITTER_CONSUMER_SECRET: "~vault:projects/anyway/prod/k8s-secret-anyway:TWITTER_CONSUMER_SECRET~"
      SELENIUM_URL: "~vault:projects/anyway/prod/k8s-secret-anyway:SELENIUM_URL~"
      BOT_TOKEN: "~vault:projects/anyway/prod/k8s-secret-anyway:BOT_TOKEN~"
      AIRFLOW_USER: "~vault:projects/anyway/prod/k8s-secret-anyway:AIRFLOW_USER~"
      AIRFLOW_PASSWORD: "~vault:projects/anyway/prod/k8s-secret-anyway:AIRFLOW_PASSWORD~"
  - name: anyway-db
    data:
      DATABASE_URL: "~vault:projects/anyway/prod/k8s-secret-anyway-db:DATABASE_URL~"
  - name: db
    data:
      DBRESTORE_AWS_ACCESS_KEY_ID: "~vault:projects/anyway/prod/aws_db_dumps_reader_user:access_key_id~"
      DBRESTORE_AWS_SECRET_ACCESS_KEY: "~vault:projects/anyway/prod/aws_db_dumps_reader_user:secret_access_key~"
      DBRESTORE_SET_ANYWAY_PASSWORD: "~vault:projects/anyway/prod/k8s-secret-db:DBRESTORE_SET_ANYWAY_PASSWORD~"
      POSTGRES_PASSWORD: "~vault:projects/anyway/prod/k8s-secret-db:POSTGRES_PASSWORD~"
  - name: db-backup
    data:
      DBDUMP_AWS_ACCESS_KEY_ID: "~vault:projects/anyway/prod/aws_db_dumps_writer_user:access_key_id~"
      DBDUMP_AWS_SECRET_ACCESS_KEY: "~vault:projects/anyway/prod/aws_db_dumps_writer_user:secret_access_key~"
      DBDUMP_PASSWORD: "~vault:projects/anyway/prod/k8s-secret-db-backup:DBDUMP_PASSWORD~"
