airflowImage: ghcr.io/data-for-change/anyway-etl/anyway-etl-airflow:v0.0.51
airflowImageDev: ghcr.io/data-for-change/anyway-etl/anyway-etl-airflow:62f331e0db002625df098d55a96a9d01f035a58b
anywayReportsImage: docker.pkg.github.com/data-for-change/anyway-reports/anyway-reports:sha-d28007a
dbBackupImage: docker.pkg.github.com/data-for-change/anyway/db_backup:sha-46934cc
dbImage: docker.pkg.github.com/data-for-change/anyway/db:sha-46934cc
etlImage: docker.pkg.github.com/hasadna/anyway-etl/anyway-etl:55a7c1ddb4610b2f75f88db8615f373b62c9f226
etlNginxImage: ghcr.io/data-for-change/anyway-etl/anyway-etl-nginx:v0.0.51
etlNginxImageDev: ghcr.io/data-for-change/anyway-etl/anyway-etl-nginx:62f331e0db002625df098d55a96a9d01f035a58b
image: docker.pkg.github.com/data-for-change/anyway/anyway:sha-46934cc
imageDev: docker.pkg.github.com/data-for-change/anyway/anyway:sha-94960b3
nginxImage: docker.pkg.github.com/data-for-change/anyway/nginx:sha-46934cc
nginxImageDev: docker.pkg.github.com/data-for-change/anyway/nginx:sha-94960b3
