airflowImage: docker.pkg.github.com/hasadna/anyway-etl/anyway-etl-airflow:v0.0.36
airflowImageDev: docker.pkg.github.com/hasadna/anyway-etl/anyway-etl-airflow:425f5733261da426e2dec22f9a864c17702a6aeb
anywayReportsImage: docker.pkg.github.com/hasadna/anyway-reports/anyway-reports:sha-12fe388
dbBackupImage: docker.pkg.github.com/hasadna/anyway/db_backup:sha-e04157e
dbImage: docker.pkg.github.com/hasadna/anyway/db:sha-e04157e
etlImage: docker.pkg.github.com/hasadna/anyway-etl/anyway-etl:55a7c1ddb4610b2f75f88db8615f373b62c9f226
etlNginxImage: docker.pkg.github.com/hasadna/anyway-etl/anyway-etl-nginx:v0.0.36
etlNginxImageDev: docker.pkg.github.com/hasadna/anyway-etl/anyway-etl-nginx:425f5733261da426e2dec22f9a864c17702a6aeb
image: docker.pkg.github.com/hasadna/anyway/anyway:sha-e04157e
imageDev: docker.pkg.github.com/hasadna/anyway/anyway:sha-a715fd5
nginxImage: docker.pkg.github.com/hasadna/anyway/nginx:sha-e04157e
nginxImageDev: docker.pkg.github.com/hasadna/anyway/nginx:sha-a715fd5
