selenium-grid:
  ingress:
    enabled: true
    className: nginx
    hostname: selenium.dataforchange.org.il
  chromeNode:
    enabled: true
    replicas: 1
    resources:
      requests:
        cpu: 300m
        memory: 1500Mi
      limits:
        memory: 2000Mi
  firefoxNode:
    enabled: false
  edgeNode:
    enabled: false
