dockerDaemonConfig:
  "log-driver": "json-file"
  "log-opts":
    "max-size": "100m"
    "max-file": "5"
    "compress": "true"

terraformStateDb:
  resources:
    requests:
      memory: 250Mi
      cpu: 50m
    limits:
      memory: 500Mi
      cpu: 100m

secrets:
  - name: terraform-state-db
    data:
      POSTGRES_PASSWORD: "~vault:projects/iac/terraform:backend-db-password~"
      # openssl req -new -x509 -days 365 -nodes -text -out server.crt \
      #  -keyout server.key -subj "/CN=terraform-state-db.localhost"
      server.key: "~vault:projects/iac/terraform:state_db_server.key~"
      server.crt: "~vault:projects/iac/terraform:state_db_server.crt~"
